Packages = proselint, write-good

StylesPath = .
Vocab = project

# F: Use views for comments/strings, clear keys from accept.txt.
# [formats]
# editorconfig = ini

[*]
BasedOnStyles = Vale, proselint, write-good
write-good.E-Prime = off
write-good.Passive = off

[*.{editorconfig,ini,json,toml,yaml,yml}]
View = configs

[*.ts]
View = sources

# F: Use the sources view.
[*.sh]
Vale.Spelling = off
proselint.Typography = off
