Packages = proselint, write-good

StylesPath = .
Vocab = project

[*]
write-good.E-Prime = off
write-good.Passive = off

[*.{md,txt}]
BasedOnStyles = Vale, proselint, write-good

[*.{json,toml,yaml,yml}]
BasedOnStyles = Vale, proselint, write-good
View = configs

[*.ts]
BasedOnStyles = Vale, proselint, write-good
View = sources

# F: Use the sources view.
[*.sh]
BasedOnStyles = Vale, proselint, write-good
Vale.Spelling = off
proselint.Typography = off
